- name: play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: play variables from files
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: print play variables from file
      ansible.builtin.debug:
        msg: URL = {{ URL }}

